
CREATE TABLE IF NOT EXISTS account(
    id SERIAL,
    email VARCHAR(50) UNIQUE,
    password VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS session(
    id serial PRIMARY KEY,
	user_id BIGINT UNIQUE,
	user_token VARCHAR(300) UNIQUE NOT NULL, 
	is_expire BOOLEAN,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES account(id)
);
